// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOgUhaL9yBQbHarq9SI3l_t3ELwPLlzk',
    appId: '1:1045504523572:web:98e96219bb7c073bfef961',
    messagingSenderId: '1045504523572',
    projectId: 'medical-authentication-6a1ed',
    authDomain: 'medical-authentication-6a1ed.firebaseapp.com',
    storageBucket: 'medical-authentication-6a1ed.appspot.com',
    measurementId: 'G-CTW88DTVJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP85d51BTCsU3nU3cQEwtR_Db4-MqOteI',
    appId: '1:1045504523572:android:dba5b01d862528a3fef961',
    messagingSenderId: '1045504523572',
    projectId: 'medical-authentication-6a1ed',
    storageBucket: 'medical-authentication-6a1ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaU1SiaOeVhP1HOl1dGtMmHAtCmPFSqWc',
    appId: '1:1045504523572:ios:030f4d2c158525d7fef961',
    messagingSenderId: '1045504523572',
    projectId: 'medical-authentication-6a1ed',
    storageBucket: 'medical-authentication-6a1ed.appspot.com',
    iosBundleId: 'com.example.healthApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaU1SiaOeVhP1HOl1dGtMmHAtCmPFSqWc',
    appId: '1:1045504523572:ios:1d24cb2510f6006efef961',
    messagingSenderId: '1045504523572',
    projectId: 'medical-authentication-6a1ed',
    storageBucket: 'medical-authentication-6a1ed.appspot.com',
    iosBundleId: 'com.example.healthApp2.RunnerTests',
  );
}
